carpooling/carpooling/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('passaggi/', include('passaggi.urls')),
    path('', RedirectView.as_view(url='/passaggi/', permanent=True)),

]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

carpooling/passaggi/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.index, name='index'),
   path('type_vehicles/', views.Type_VehiclesListView.as_view(), name='type_vehicles'),
   path('type_vehicle/<int:pk>', views.Type_VehicleDetailView.as_view(), name='type_vehicle-detail'),
   path('path_offers/', views.Path_OfferListView.as_view(), name='path_offers'),
   path('path_offer/<int:pk>', views.Path_OfferDetailView.as_view(), name='path_offer-detail'),
   path('user/<int:pk>', views.UserDetailView.as_view(), name='user-detail'),
   path('vehicle/<int:pk>', views.VehicleDetailView.as_view(), name='vehicle-detail'),
]

carpooling/passaggi/models.py
from django.db import models
import uuid
# Create your models here.
class Type_Vehicle(models.Model):
    """Model representing a type vehicle."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    description = models.CharField(max_length=45, help_text='Enter a type vehicle')
    def get_absolute_url(self):
        """Returns the url to access a detail record for this type vehicle."""
        return reverse('type_vehicle-detail', args=[str(self.id)])
    def __str__(self):
        """String for representing the Model object."""
        return self.description
    class Meta:
        ordering = ['id']
class User(models.Model):
    """Model representing an user."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    email = models.CharField(max_length=45, help_text='Enter an email')
    encrypted_password=models.CharField(max_length=45)
    admin=models.BooleanField()
    active=models.BooleanField()
    def get_absolute_url(self):
        """Returns the url to access a detail record for this user."""
        return reverse('user-detail', args=[str(self.id)])
    def __str__(self):
        """String for representing the Model object."""
        return self.email
class Profile( models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=50, help_text='Enter the name')
    surname = models.CharField(max_length=50, help_text='Enter the surname')
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    mobile = models.CharField(max_length=20)
    description=models.TextField(max_length=1000)
    user_id = models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return f'{self.name},{self.surname}'
class Vehicle( models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    brand = models.CharField(max_length=45, help_text='Enter the brand')
    model = models.CharField(max_length=45, help_text='Enter the model')
    colour = models.CharField(max_length=45)
    motor = models.CharField(max_length=20)
    user_id = models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    type_vehicle_id = models.ForeignKey('Type_vehicle', on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return f'{self.brand},{self.model}'
class Preference(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    conversation=models.BooleanField()
    animal=models.BooleanField()
    smoke=models.BooleanField()
    music=models.BooleanField()
    user_id=models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return f'{self.animal},{self.smoke},{self.conversation},{self.music}'
class Scores(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    scores=models.IntegerField()
    count=models.IntegerField()
    total=models.IntegerField()
    user_id=models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return f'{self.scores},{self.count},{self.total}'
class Path_Offer( models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    departure = models.CharField(max_length=100, help_text='Enter the departure')
    arrive = models.CharField(max_length=100, help_text='Enter the arrive')
    data_partenza=models.DateField(help_text="Enter la data di partenza")
    data_arrivo=models.DateField(help_text="Enter la data di arrivo")
    ora_partenza = models.DateTimeField(help_text="Enter l'ora di partenza")
    ora_arrivo = models.DateTimeField(help_text="Enter l'ora di arrivo")
    user_id = models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    vehicle_id = models.ForeignKey('Vehicle', on_delete=models.SET_NULL, null=True)
    max_avalaible=models.IntegerField()
    price=models.FloatField()
    full=models.BooleanField()
    booked=models.BooleanField()
    def get_absolute_url(self):
        """Returns the url to access a detail record for this path offer."""
        return reverse('path_offer-detail', args=[str(self.id)])
    def __str__(self):
        return f'{self.departure},{self.arrive},{self.data_partenza},{self.data_arrivo},{self.ora_partenza},{self.ora_arrivo}'
    class Meta:
        ordering = ['id']
class Feedback(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    scores=models.IntegerField()
    feedback=models.TextField()
    title=models.CharField(max_length=45)
    user_id=models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    path_offer_id=models.ForeignKey('Path_Offer', on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return f'{self.feedback},{self.title},{self.scores}'
class Feedback_Path(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    booked=models.IntegerField()
    user_id=models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    path_offer_id=models.ForeignKey('Path_Offer', on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return f'{self.user_id},{self.path_offer_id},{self.booked}'
class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user_id=models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    dest_user_id = models.CharField(max_length=45)
    path_offer_id=models.ForeignKey('Path_Offer', on_delete=models.SET_NULL, null=True)
    title=models.CharField(max_length=45)
    message=models.CharField(max_length=45)
    read=models.BooleanField()
    def __str__(self):
        return f'{self.user_id},{self.dest_user_id},{self.title},{self.message}'

carpooling/passaggi/views.py
from django.shortcuts import render
from passaggi.models import Type_Vehicle, Path_Offer, User, Vehicle

from django.views import generic
# Create your views here.
def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_type_vehicles = Type_Vehicle.objects.all().count()
    num_path_offers = Path_Offer.objects.all().count()


    context = {

       'num_type_vehicles': num_type_vehicles,
        'num_path_offers': num_path_offers,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)
class Type_VehiclesListView(generic.ListView):
    model = Type_Vehicle
    paginate_by = 10
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(Type_VehiclesListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context
    def get_queryset(self):
        return Type_Vehicle.objects.filter(description__icontains='i')[:5] # Get 5 books containing the title war
    template_name = 'type_vehicles/my_arbitrary_template_name_list.html'  # Specify your own template name/location
class Type_VehicleDetailView(generic.DetailView):
    model = Type_Vehicle

    def type_vehicle_detail_view(request, primary_key):
        try:
            type_vehicle = Type_Vehicle.objects.get(pk=primary_key)
        except Book.DoesNotExist:
            raise Http404('Type Vehicle does not exist')

        return render(request, 'passaggi/type_vehicle_detail.html', context={'type_vehicle': type_vehicle})
class Path_OfferListView(generic.ListView):
    model = Path_Offer
    paginate_by = 10
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(Path_OfferListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context
    def get_queryset(self):
        return Path_Offer.objects.filter(departure__icontains='n')[:5]
    template_name = 'path_offers/my_arbitrary_template_name_list.html'  # Specify your own template name/location
class Path_OfferDetailView(generic.DetailView):
    model = Path_Offer

    def path_offer_detail_view(request, primary_key):
        try:
            path_offer = Path_Offer.objects.get(pk=primary_key)
        except Path_Offer.DoesNotExist:
            raise Http404('Path Offer does not exist')

        return render(request, 'passaggi/path_offer_detail.html', context={'path_offer': path_offer})
class UserDetailView(generic.DetailView):
    model= User
    def user_detail_view(request, primary_key):
        try:
            user:User.objects.get(pk=primary_key)
        except User.DoesNotExist:
            raise Http404('User does not exist')
        return render(request, 'passaggi/user_detail.html',context={'user':user})
class VehicleDetailView(generic.DetailView):
    model= Vehicle
    def vehicle_detail_view(request, primary_key):
        try:
            vehicle:Vehicle.objects.get(pk=primary_key)
        except Vehicle.DoesNotExist:
            raise Http404('Vehicle does not exist')
        return render(request, 'passaggi/vehicle_detail.html',context={'vehicle': vehicle})

carpooling/passaggi/templates/passaggi/path_offer_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Departure: {{ path_offer.departure}}</h1>
  <p><strong>Arrive:</strong>{{ path_offer.arrive}}</p>
  <p><strong>Date of departure:</strong> {{ path_offer.data_partenza}}</p>
  <p><strong>Date of arrive:</strong> {{ path_offer.data_arrivo}}</p>
  <p><strong>Departure's time:</strong> {{path_offer.ora_partenza}}</p>
  <p><strong>Arrive's time:</strong> {{path_offer.ora_arrivo}}</p>
<p><strong>Booked:</strong>{{ path_offer.booked}}</p>
  <p><strong>Full:</strong> {{ path_offer.full}}</p>
  <p><strong>Price:</strong> {{ path_offer.price}}</p>
  <p><strong>Max Available:</strong> {{path_offer.max_available}}</p>
<a href="{% url 'user-detail' path_offer.user.pk %}">{{ path_offer.user_id}}</a>
<a href="{% url 'vehicle-detail' path_offer.vehicle.pk %}">{{ path_offer.vehicle_id}}</a>
{% for feedback in path_offer.feedback_set.all %}
  <p><strong>Scores:</strong>{{ feedback.scores}}</p>
  <p><strong>Feedback:</strong> {{feedback.feedback}}</p>
  <p><strong>Title:</strong> {{ feedback.title}}</p>
  <a href="{% url 'user-detail' feedback.user.pk %}">{{ feedback.user_id}}</a>
   {%endfor %}
  {% endblock %}

carpooling/passaggi/templates/passaggi/path_offer_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Path offer List</h1>
  {% if path_offer_list %}
  <ul>
    {% for path_offer in path_offer_list %}
      <li>
        <a href="{{ path_offer.get_absolute_url }}">{{ path_offer.departure }}</a> ({{path_offer.arrive}})({{path_offer.data_partenza}})({{path_offer.data_arrivo}})({{path_offer.ora_partenza}})({{path_offer.ora_arrivo}})({{path_offer.booked}})({{path_offer.full}})({{path_offer.price}})({{path_offer.max_available}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no path offers.</p>
  {% endif %} 
{% endblock %}

carpooling/passaggi/templates/passaggi/type_vehicle_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Description: {{ type_vehicle.description}}</h1>

    {% endblock %}

carpooling/passaggi/templates/passaggi/type_vehicle_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Type Vehicle List</h1>
  {% if type_vehicle_list %}
  <ul>
    {% for type_vehicle in type_vehicle_list %}
      <li>
        <a href="{{ type_vehicle.get_absolute_url }}">{{ type_vehicle.description}}</a></li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no type vehicles.</p>
  {% endif %} 
{% endblock %}

carpooling/passaggi/templates/passaggi/user_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Id: {{ user.id}}</h1>

  <p><strong>Email:</strong>{{ user.email}}</p>
  <p><strong>Admin:</strong> {{ user.admin}}</p>
  <p><strong>Active:</strong> {{ user.active}}</p>
  {% for profile in user.profile_set.all %}
  <p><strong>Name:</strong>{{ profile.name}}</p>
  <p><strong>Surname:</strong> {{profile.surname}}</p>
  <p><strong>Address:</strong> {{ profile.address}}</p>
  <p><strong>City:</strong>{{ profile.city}}</p>
  <p><strong>Mobile:</strong> {{ profile.mobile}}</p>
  <p><strong>Description:</strong> {{ profile.description}}</p>
  {%endfor %}
  {% for preference in user.preference_set.all %}
  <p><strong>Conversation:</strong>{{ preference.conversation}}</p>
  <p><strong>Smoke:</strong> {{preference.smoke}}</p>
  <p><strong>Animal:</strong> {{ preference.animal}}</p>
  <p><strong>Music:</strong>{{ preference.music}}</p>
   {%endfor %}
   {% for scores in user.scores_set.all %}
  <p><strong>Scores:</strong>{{ scores.scores}}</p>
  <p><strong>Count:</strong> {{scores.count}}</p>
  <p><strong>Total:</strong> {{ scores.total}}</p>
   {%endfor %}

  {% endblock %}

carpooling/passaggi/templates/passaggi/vehicle_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Id: {{ vehicle.id}}</h1>
  <p><strong>Brand:</strong>{{ vehicle.brand}}</p>
  <p><strong>Colour:</strong>{{ vehicle.colour}}</p>
  <p><strong>Model:</strong> {{ vehicle.model}}</p>
  <p><strong>Motor:</strong> {{ vehicle.motor}}</p>
  <a href="{% url 'user-detail' vehicle.user.pk %}">{{ vehicle.user_id}}</a>
  <a href="{% url 'type_vehicle-detail' vehicle.type_vehicle.pk %}">{{ vehicle.type_vehicle_id}}</a>
  {% endblock %}